name: Tutorial
version: 1.0
author: TheAwesomeGuy47
main: com.theawesomeguy47.tutorial.Tutorial
api-version: 1.14
commands:
  heal:
    description: Heals player to maximum health.
    usage: /<command>
    aliases: [healing, healme, healmax, healall]

  feed:
    description: Feeds player to maximum saturation (hunger).
    usage: /<command>
    aliases: [ feeding, feedme, feedmax, feedall ]

  farmtime:
    description: Spawns farm animals.
    usage: /farmtime <mob> <amount>

  givewand:
    description: Gives you the magical Stick of Truth.
    usage: /givewand

  select:
    description: Opens the selection screen.
    usage: /select